#!/usr/bin/env bash
#
# Post the preview on the pull request. This is the one thing the GitHub Actions
# workflow got for free from pulumi/actions, and the one piece of the pipeline
# that still needs a GitHub credential — an outbound one, held in Secret Manager
# and used from inside Google Cloud, rather than an identity GitHub holds.
#
# It is optional on purpose. With no token stored, the preview is still in the
# build log and the pipeline does not fail; a missing comment is a worse outcome
# than a failed deploy only if it goes unnoticed, so it says so loudly.
set -euo pipefail

: "${MODE:?MODE must be preview or apply}"

if [[ "$MODE" != "preview" ]]; then
  exit 0
fi

PREVIEW_OUT=${PREVIEW_OUT:-/workspace/preview.txt}
GITHUB_TOKEN=${GITHUB_TOKEN:-}

# "none" is the sentinel the setup script stores, because Secret Manager will
# not hold an empty payload and the secret has to exist for the build to start.
if [[ -z "${GITHUB_TOKEN//[[:space:]]/}" || "$GITHUB_TOKEN" == "none" ]]; then
  echo "No GitHub token stored — skipping the pull request comment."
  echo "The preview is above in this build's log."
  echo "To enable comments, store a fine-grained token carrying only"
  echo "Pull requests: read and write —"
  echo "  gcloud secrets versions add github-pr-token --data-file=-"
  exit 0
fi

if [[ ! -s "$PREVIEW_OUT" ]]; then
  echo "No preview output to post." >&2
  exit 0
fi

: "${REPO:?REPO must be owner/name}"
: "${PR:?PR must be the pull request number}"
: "${BUILD_ID:?BUILD_ID must be set}"
: "${GOOGLE_PROJECT:?GOOGLE_PROJECT must be set}"

# Python rather than jq: the JSON has to carry arbitrary preview output, and
# hand-escaping that in shell is how a stray quote in a resource name turns into
# a malformed request that reads like an auth failure.
python3 - "$PREVIEW_OUT" > /workspace/comment.json <<'PY'
import json, os, sys

body = open(sys.argv[1], encoding="utf-8", errors="replace").read()

# GitHub rejects a comment body over 65536 characters. A preview of a large
# change can exceed that, and a truncated preview with a pointer to the full log
# beats no comment at all.
limit = 60000
truncated = len(body) > limit
if truncated:
    body = body[-limit:]

project = os.environ["GOOGLE_PROJECT"]
build = os.environ["BUILD_ID"]
log = (
    f"https://console.cloud.google.com/cloud-build/builds/{build}"
    f"?project={project}"
)

parts = ["### Pulumi preview — stack `dev`\n"]
if truncated:
    parts.append("_Trimmed to the last 60,000 characters._\n")
parts.append(f"```\n{body}\n```\n")
parts.append(f"\n[Full build log]({log})\n")
parts.append("\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n")

print(json.dumps({"body": "".join(parts)}))
PY

status=$(curl -sS -o /workspace/comment-response.json -w '%{http_code}' \
  -X POST \
  -H "Authorization: Bearer ${GITHUB_TOKEN}" \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  --data @/workspace/comment.json \
  "https://api.github.com/repos/${REPO}/issues/${PR}/comments")

if [[ "$status" != "201" ]]; then
  echo "GitHub rejected the comment (HTTP $status):" >&2
  cat /workspace/comment-response.json >&2
  # Not fatal: the preview itself succeeded, and failing the build here would
  # report a healthy program as a broken one.
  exit 0
fi

echo "Preview posted on ${REPO}#${PR}."
